# Generated by Django 2.1.1 on 2021-03-15 16:14

import apps.notes.enum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Instance marked Active')),
                ('comments', models.TextField()),
                ('comment_heirarchy', django_enumfield.db.fields.EnumField(default=1, enum=apps.notes.enum.CommentHeirarchy)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notes.Comment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'notes_comment',
            },
        ),
    ]
