# Generated by Django 2.1.1 on 2021-03-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default='2021-03-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comment_user', to='users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_user', to='users.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
